config/routes.rb
Rails.application.routes.draw do
  root               "static_pages#home"
  get    "help"   => "static_pages#help"
  get    "about"  => "static_pages#about"
  get    "signup" => "users#new"
  get    "login"  => "sessions#new"
  post   "login"  => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  resources :categories do
    resources :lessons
  end
  resources :words
  namespace :admin do
    root "users#index"
    resources :users
    resources :categories
    resources :words
  end
  resources :relationships, only: [:index, :create, :destroy]
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    if logged_in?
      if admin_user?
        redirect_to admin_users_path
      else
        @activities = current_user.following_activities.paginate page: params[:page]
      end
    end
  end

  def help
  end

  def about
  end
end

app/views/static_pages/about.html.erb
<% provide :title, t(:about) %>
<h1><%= t :app_name %></h1>
<p>
  <%= t :about_msg %>
</p>

app/views/static_pages/help.html.erb
<% provide :title, t(:help) %>
<h1><%= t :app_name %></h1>
<p>
  <%= t :help_msg %>
</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render "shared/user_info" %>
      </section>
      <section class="stats">
        <%= render "shared/stats" %>
      </section>
    </aside>
    <aside class="col-md-8">
      <section>
        <%= link_to t(:all_categories), categories_path, class: "btn btn-lg btn-primary" %>
        <%= link_to t(:all_words), words_path, class: "btn btn-lg btn-primary" %>
      </section>
      <section>
        <ul class="users">
          <%= render @activities %>
        </ul>
        <%= will_paginate @activities %>
      </section>
    </aside>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1><%= t :welcome_msg %></h1>
    <%= link_to t(:sign_up_now), signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>