config/routes.rb
Rails.application.routes.draw do
  root               "static_pages#home"
  get    "help"   => "static_pages#help"
  get    "about"  => "static_pages#about"
  get    "signup" => "users#new"
  get    "login"  => "sessions#new"
  post   "login"  => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  resources :categories do
    resources :lessons
  end
  resources :words
  namespace :admin do
    root "users#index"
    resources :users
    resources :categories
    resources :words
  end
  resources :relationships, only: [:index, :create, :destroy]
end

app/models/word.rb
class Word < ActiveRecord::Base
  belongs_to :category
  has_many :results
  has_many :answers, dependent: :destroy
  has_many :lessons, through: :results
  accepts_nested_attributes_for :answers,
    reject_if: lambda {|attribute| attribute[:content].blank?},
    allow_destroy: true
  validates :content, presence: true
  before_save :must_be_a_correct_answer

  scope :learned, ->user_id, category_id{
    where("id in (select results.word_id from results join answers
    on results.answer_id = answers.id where answers.is_correct = 't' and
    lesson_id in (select id from lessons where
    category_id = #{category_id} and user_id = #{user_id}))")}

  scope :not_learned, ->user_id, category_id{
    where("id in(select id from words where category_id = #{category_id}
    and id not in (select results.word_id from results join answers on
    results.answer_id = answers.id where answers.is_correct = 't' and
    lesson_id in (select id from lessons where
    category_id = #{category_id} and user_id = #{user_id})))")}

  OPTION = {learned: :learned, not_learned: :not_learned, all_word: :all_word}

  class << self
    def filter_words category, current_filter, current_user
      case current_filter
      when "learned"
        self.learned current_user.id, category.id
      when "not_learned"
        self.not_learned current_user.id, category.id
      else
        category.words
      end
    end
  end

  private
  def must_be_a_correct_answer
    unless self.answers.select{|answer| answer.is_correct}.size == 1
      errors.add " ", I18n.t("must_be_a_answer_correct")
    end
  end
end

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :admin_user, only: [:index, :new, :edit, :update, :create]

  def index
    @words = Word.paginate page: params[:page]
  end

  def new
    @categories = Category.all
    @word = Word.new
    @word.answers.new
  end

  def create
    @word = Word.new word_params
    if @word.save
      flash[:success] = t :word_created
      redirect_to admin_words_path
    else
      @categories = Category.all
      render :new
    end
  end

  def edit
    @categories = Category.all
    @word = Word.find params[:id]
  end

  def update
    @word = Word.find params[:id]
    if @word.update_attributes word_params
      flash[:success] = t :word_updated
      redirect_to admin_words_path
    else
      render :edit
    end
  end

  def destroy
    @word = Word.find params[:id]
    @word.destroy
    flash[:success] = t :word_deleted
    redirect_to admin_words_path
  end

  private
  def word_params
    params.require(:word).permit :content, :category_id,
      answers_attributes: [:id, :content, :is_correct, :_destroy]
  end

  def admin_user
    redirect_to(root_url) unless current_user.is_admin?
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user
  before_action :not_admin_user

  def index
    @categories = Category.all
    if params[:category_id]
      @category = Category.find_by id: params[:category_id]
    else
      @category = Category.first
    end
    @words = Word.filter_words(@category, params[:option], current_user)
      .paginate page: params[:page]
  end
end

app/views/admin/words/_answer_fields.html.erb
<div class="answer_fields">
  <div class="form-group">
    <div class="col-sm-8 div1">
      <%= f.text_field :content, class: "form-control" %>
    </div>
    <div class="col-sm-2 div2">
      <%= f.check_box :is_correct %>
    </div>
    <div class="col-sm-2 div3">
      <%= link_to_remove_fields t(:remove), f %>
    </div>
  </div>
</div>

app/views/admin/words/_word.html.erb
<li>
  <%= link_to word.content, edit_admin_word_path(word) %>
  <% if current_user.is_admin? %>
    | <%= link_to t(:delete), admin_word_path(word), method: :delete,
      data: {confirm: t(:delete_confirm)} %>
  <% end %>
</li>

app/views/admin/words/_word_form.html.erb
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @word], html: {class: "form-horizontal"} do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= f.select :category_id, options_from_collection_for_select(@categories,
        "id", "category_name") %>
      <%= f.label :content %>
      <%= f.text_field :content, class: "form-control" %>
      <div id="answers_list">
        <%= f.fields_for :answers do |answer_builder| %>
          <%= render "answer_fields", f: answer_builder %>
        <% end %>
      </div>
      <p><%= link_to_add_fields t(:add_answer), f, :answers %></p>
      <%= f.submit t(:word_create), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/words/edit.html.erb
<% provide :title, t(:word_edit) %>
<h1><%= t :word_edit %></h1>
<%= render "word_form" %>

app/views/admin/words/index.html.erb
<% provide :title, t(:all_words) %>
<h1><%= t :all_words %></h1>
<div class="row text-center">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to t(:word_create), new_admin_word_path, class: "btn btn-primary" %>
    <ul class="users">
      <%= render @words %>
    </ul>
    <%= will_paginate %>
  </div>
</div>

app/views/admin/words/new.html.erb
<% provide :title, t(:word_create) %>
<h1><%= t :word_create %></h1>
<%= render "word_form" %>