config/routes.rb
Rails.application.routes.draw do
  root               "static_pages#home"
  get    "help"   => "static_pages#help"
  get    "about"  => "static_pages#about"
  get    "signup" => "users#new"
  get    "login"  => "sessions#new"
  post   "login"  => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  resources :categories do
    resources :lessons
  end
  resources :words
  namespace :admin do
    root "users#index"
    resources :users
    resources :categories
    resources :words
  end
  resources :relationships, only: [:index, :create, :destroy]
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :lessons
  has_many :words, dependent: :destroy
  validates :category_name, presence: true, length: {maximum:50},
    uniqueness: true
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user
  before_action :find_category, only: [:edit, :update, :destroy]

  def index
    @categories = Category.paginate page: params[:page]
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t :category_created
      redirect_to admin_categories_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t :category_updated
      redirect_to admin_categories_path
    else
      render :edit
    end
  end

  def destroy
    @category.destroy
    flash[:success] = t :category_deleted
    redirect_to admin_categories_path
  end

  private
  def admin_user
    redirect_to(root_url) unless current_user.is_admin?
  end

  def category_params
    params.require(:category).permit :category_name
  end

  def find_category
    @category = Category.find params[:id]
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :logged_in_user
  before_action :not_admin_user

  def index
    @categories = Category.paginate page: params[:page]
  end
end

app/views/admin/categories/_category.html.erb
<li>
  <%= link_to category.category_name, edit_admin_category_path(category) %>
  <% if current_user.is_admin? %>
    | <%= link_to t(:delete), admin_category_path(category), method: :delete,
      data: {confirm: t(:delete_confirm)} %>
  <% end %>
</li>

app/views/admin/categories/edit.html.erb
<% provide :title, t(:category_edit) %>
<h1><%= t :category_edit %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @category] do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= f.label :category_name %>
      <%= f.text_field :category_name, class: "form-control" %>
      <%= f.submit t(:category_edit), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/admin/categories/index.html.erb
<% provide :title, t(:all_categories) %>
<h1><%= t :all_categories %></h1>
<div class="row text-center">
  <div class="col-md-6 col-md-offset-3">
    <%= link_to t(:category_create), new_admin_category_path, class: "btn btn-primary" %>
    <ul class="users">
      <%= render @categories %>
    </ul>
    <%= will_paginate %>
  </div>
</div>

app/views/admin/categories/new.html.erb
<% provide :title, t(:category_create) %>
<h1><%= t :category_create %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for [:admin, @category] do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= f.label :category_name %>
      <%= f.text_field :category_name, class: "form-control" %>
      <%= f.submit t(:category_create), class: "btn btn-primary" %>
    <% end %>
  </div>
</div>