config/routes.rb
Rails.application.routes.draw do
  root               "static_pages#home"
  get    "help"   => "static_pages#help"
  get    "about"  => "static_pages#about"
  get    "signup" => "users#new"
  get    "login"  => "sessions#new"
  post   "login"  => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users
  resources :categories do
    resources :lessons
  end
  resources :words
  namespace :admin do
    root "users#index"
    resources :users
    resources :categories
    resources :words
  end
  resources :relationships, only: [:index, :create, :destroy]
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token
  has_many :activities, dependent: :destroy
  has_many :lessons, dependent: :destroy
  has_many :active_relationships,  class_name: Relationship.name,
    foreign_key: :follower_id,
    dependent: :destroy
  has_many :passive_relationships, class_name: Relationship.name,
    foreign_key: :followed_id,
    dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  before_save {self.email = email.downcase}
  validates :name,  presence: true, length: {maximum: 50}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum: 255},
    format: {with: VALID_EMAIL_REGEX},
    uniqueness: {case_sensitive: false}
  has_secure_password
  validates :password, presence: true, length: {minimum: 6}

  def User.digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
      BCrypt::Engine.cost
      BCrypt::Password.create string, cost: cost
  end

  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attributes remember_digest: User.digest(remember_token)
  end

  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attributes remember_digest: nil
  end

  def follow other_user
    active_relationships.create followed_id: other_user.id
  end

  def unfollow other_user
    active_relationships.find_by(followed_id: other_user.id).destroy
  end

  def following? other_user
    following.include? other_user
  end

  def following_activities
    Activity.where "user_id in (?)", self.following.pluck(:id)
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :logged_in_user
  before_action :admin_user

  def index
    @users = User.paginate page: params[:page]
  end

  def edit
    @user = User.find params[:id]
  end

  def update
    @user = User.find params[:id]
    if @user.update_attributes(user_params)
      flash[:success] = t :profile_updated
      redirect_to admin_users_path
    else
      render :edit
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = t :user_deleted
    redirect_to admin_users_path
  end

  private
  def admin_user
    redirect_to(root_url) unless current_user.is_admin?
  end

  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
    :following, :followers]
  before_action :not_admin_user, except: [:new]
  before_action :correct_user, only: [:edit, :update]
  before_action :find_user, only: [:show, :edit, :update, :following,
    :followers]

  def index
    @users = User.paginate page: params[:page]
  end

  def show
    @activities = @user.activities.paginate page: params[:page]
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      flash[:success] = t :welcome_msg
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = t :profile_updated
      redirect_to @user
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit :name, :email, :password,
      :password_confirmation
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = t :please_log_in
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find params[:id]
    redirect_to root_url unless current_user? @user
  end

  def find_user
    @user = User.find params[:id]
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for user, options = {size: 80}
    gravatar_id = Digest::MD5::hexdigest user.email.downcase
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag gravatar_url, alt: user.name, class: "gravatar"
  end
end

app/views/admin/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, edit_admin_user_path(user) %>
  <% if current_user.is_admin? && !current_user?(user) %>
    | <%= link_to t(:delete), admin_user_path(user), method: :delete,
      data: {confirm: t(:delete_confirm)} %>
  <% end %>
</li>

app/views/admin/users/edit.html.erb
<% provide :title, t(:edit_user) %>
<h1><%= t :update_your_profile %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for  [:admin, @user] do |f| %>
      <%= render "shared/error_messages", object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control" %>
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control" %>
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control" %>
      <%= f.label :password_confirmation, t(:confirmation) %>
      <%= f.password_field :password_confirmation, class: "form-control" %>
      <%= f.submit t(:save_changes), class: "btn btn-primary" %>
    <% end %>
    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank"><%= t :change %></a>
    </div>
  </div>
</div>

app/views/admin/users/index.html.erb
<% provide :title, t(:all_users) %>
<h1><%= t :all_users %></h1>
<ul class="users">
  <%= render @users %>
</ul>
<%= will_paginate %>